version: '3.9'

services:
  web:
    build: .
    command: bash -c "python project/manage.py makemigrations && python project/manage.py migrate && python project/manage.py test && python project/manage.py runserver"
    container_name: bitstocks
    restart: unless-stopped
    volumes:
      - .:/usr/src/app/